/*
 Nombre del programa: La gran despensa
 Fecha de creación: 30/04/2021
 Fecha de entrega 06/05/2021
Autor: Ivan Cordova Rodriguez
 */
package Frames;

import Methods.metodoVenta;
import Methods.producto;
import Methods.venta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan
 */
public class eliminarVenta extends javax.swing.JFrame {

    /**
     * Creates new form eliminarVenta
     */
    // ----------------- Creamos el modelo por defecto de la Jtabla Ventas ---------------------
    DefaultTableModel modeloVenta = new DefaultTableModel(){
        public boolean isCellEditable(int row, int column) { 
            return false; 
        }
    };
    // Inicializamos las variables globales
    metodoVenta metodos = new metodoVenta();
    javax.swing.JFrame padre ;
    
    public eliminarVenta() {
        initComponents();
//        // Agregamos al modelo las columnas de la tabla 
//        this.setLocationRelativeTo(null);//Centra la ventana
//        modeloVenta.addColumn("Id venta");
//        modeloVenta.addColumn("Nombre usuario");
//        modeloVenta.addColumn("Fecha de venta");
//        modeloVenta.addColumn("Suma de venta");
//        this.tbl_ventas.setModel(modeloVenta);
//        llenarTabla(); // Usamos el método para llenar el Jtable de ventas 
    }

    public eliminarVenta(javax.swing.JFrame padre) {
        initComponents();
        // Agregamos al modelo las columnas de la tabla 
        this.setLocationRelativeTo(null);//Centra la ventana
        this.padre = padre;

        modeloVenta.addColumn("Id venta");
        modeloVenta.addColumn("Nombre usuario");
        modeloVenta.addColumn("Fecha de venta");
        modeloVenta.addColumn("Suma de venta");
        this.tbl_ventas.setModel(modeloVenta);
        llenarTabla(); // Usamos el método para llenar el Jtable de ventas 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ventas = new javax.swing.JTable();
        btn_Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/v_lista.png"))); // NOI18N
        jLabel1.setText("Lista de ventas");

        tbl_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ventasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ventas);

        btn_Regresar.setBackground(new java.awt.Color(66, 108, 180));
        btn_Regresar.setText("Regresar");
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ventasMouseClicked
        // Controlamos el evento Mouse Clicked para seleccionar la venta que se va a eliminar 
        int seleccion = this.tbl_ventas.rowAtPoint(evt.getPoint());//Guardamos el índice de la fila que se selecciona

        if(JOptionPane.showConfirmDialog(null, "Quiere eliminar el producto seleccionado", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0){
            //Eliminamos la venta del Jtable y con el método eliminar Venta lo eliminamos de la base de datos 
            DefaultTableModel modelo = (DefaultTableModel) tbl_ventas.getModel();
            metodos.eliminarVenta(String.valueOf(modelo.getValueAt(seleccion, 0)));
            modelo.removeRow(seleccion);
        }

    }//GEN-LAST:event_tbl_ventasMouseClicked

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
         // ----------- Control del botón para cancelar la venta actual ---------------
        this.padre.setVisible(true); // Hacemos visible al padre 
        this.dispose(); //Cerramos le proceso actual 
    }//GEN-LAST:event_btn_RegresarActionPerformed

    public void llenarTabla(){
        // Método para llenar el Jtable de ventas 
        ArrayList<venta> lista = metodos.listaVentas();
        for (venta ob : lista) {
            Object[] listaTabla = new Object[4];
            listaTabla[0] = ob.idVenta;
            listaTabla[1] = ob.nombreUsuario;
            listaTabla[2] = ob.fechaVenta;
            listaTabla[3] = ""+ob.sumaFinal;
            modeloVenta.addRow(listaTabla);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eliminarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eliminarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eliminarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eliminarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eliminarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ventas;
    // End of variables declaration//GEN-END:variables
}
