/*
 Nombre del programa: La gran despensa
 Fecha de creación: 30/04/2021
 Fecha de entrega 19/05/2021
 Autor: Ivan Cordova Rodriguez
 */
package Frames;

import Methods.metodoVenta;
import Methods.producto;
import Methods.venta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan
 */
public class modificarVenta extends javax.swing.JFrame {
    
    //Bloqueamos las dos tablas para que no se pueden modificar 
    DefaultTableModel modeloVenta = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    //Bloqueamos las dos tablas para que no se pueden modificar
    DefaultTableModel modeloProducto = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    // Inicializamos las variables globales
    metodoVenta metodos = new metodoVenta();
    javax.swing.JFrame padre;
    

    public modificarVenta() {
        initComponents();
    }
    
    public modificarVenta(javax.swing.JFrame padre){
        initComponents();
        this.setLocationRelativeTo(null);//Centra la ventana
        this.padre = padre;

        //Agregamos las columnas a los modelos de cada tabla
        modeloVenta.addColumn("Id venta");
        modeloVenta.addColumn("Nombre usuario");
        modeloVenta.addColumn("Fecha de venta");
        modeloVenta.addColumn("Suma de venta");
        this.tbl_ventas.setModel(modeloVenta);
        
        modeloProducto.addColumn("Id Producto");
        modeloProducto.addColumn("Nombre");
        modeloProducto.addColumn("Marca");
        modeloProducto.addColumn("Precio");
        modeloProducto.addColumn("Cantidad");
        modeloProducto.addColumn("Subtotal");
        modeloProducto.addColumn("id_proventa");
        modeloProducto.addColumn("id_venta");
        this.tbl_Productos.setModel(modeloProducto);
        this.tbl_Productos.getColumnModel().getColumn(6).setMaxWidth(0);//Ocultamos la columna imagen
        this.tbl_Productos.getColumnModel().getColumn(7).setMaxWidth(0);//Ocultamos la columna imagen
        llenarTablaVentas(); // Usamos el método para llenar el Jtable de ventas
    }

        public void llenarTablaVentas(){
        // Método para llenar el Jtable de ventas 
                //Limpiamos la tabla de productos 
        DefaultTableModel modeloVentas = (DefaultTableModel) tbl_ventas.getModel();
        for (int i = 0; i < this.tbl_ventas.getRowCount(); i++) {
            modeloVentas.removeRow(i);
            i -= 1;
        }
        //Usamos el ArrayList para llenar la lista Object y pasarla a la tabla 
        ArrayList<venta> lista = metodos.listaVentas();
        for (venta ob : lista) {
            Object[] listaTabla = new Object[4];
            listaTabla[0] = ob.idVenta;
            listaTabla[1] = ob.nombreUsuario;
            listaTabla[2] = ob.fechaVenta;
            listaTabla[3] = ""+ob.sumaFinal;
            modeloVenta.addRow(listaTabla);
        }
    }
        
        
        public void limpiarTablaProductos(){
        //Limpiamos la tabla de productos 
        DefaultTableModel modeloProductos = (DefaultTableModel) tbl_Productos.getModel();
        for (int i = 0; i < this.tbl_Productos.getRowCount(); i++) {
            modeloProductos.removeRow(i);
            i -= 1;
        }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ventas = new javax.swing.JTable();
        btn_Regresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Productos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/v_lista.png"))); // NOI18N
        jLabel1.setText("Lista de productos");

        tbl_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ventasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ventas);

        btn_Regresar.setBackground(new java.awt.Color(66, 108, 180));
        btn_Regresar.setText("Regresar");
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });

        tbl_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Productos);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/v_lista.png"))); // NOI18N
        jLabel2.setText("Lista de ventas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(225, 225, 225))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ventasMouseClicked
        // --------Controlamos el evento Mouse Clicked para seleccionar la venta que se va a modificar ----------
        limpiarTablaProductos();
        //Guardamos el índice de la fila que se selecciona
        int seleccion = this.tbl_ventas.rowAtPoint(evt.getPoint());
        DefaultTableModel modeloVentas = (DefaultTableModel) tbl_ventas.getModel();
        ArrayList<producto> listaProductos = metodos.listaProducto(String.valueOf(modeloVentas.getValueAt(seleccion, 0)));
        //Usamos el ArrayList para llenar la lista Object y pasarla a la tabla 
        for (producto li : listaProductos) {
            Object[] listaTabla = new Object[8];
            listaTabla[0] = li.id_producto;
            listaTabla[1] = li.nombre;
            listaTabla[2] = li.nombre_marca;
            listaTabla[3] = li.precioVenta;
            listaTabla[4] = li.cantidad;
            listaTabla[5] = li.subTotal;
            listaTabla[6] = li.id_proventa;
            listaTabla[7] = String.valueOf(modeloVentas.getValueAt(seleccion, 0));
            modeloProducto.addRow(listaTabla);
        }
    }//GEN-LAST:event_tbl_ventasMouseClicked

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        // ----------- Control del botón para cancelar la venta actual ---------------
        this.padre.setVisible(true); // Hacemos visible al padre 
        this.dispose(); //Cerramos le proceso actual 
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void tbl_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ProductosMouseClicked
        // ------------- Acción que sé nuestra al dar click en la tabla productos  -------------------
        //Guardamos el índice de la fila que se selecciona
        int seleccion = this.tbl_Productos.rowAtPoint(evt.getPoint());
        DefaultTableModel modeloProductos = (DefaultTableModel) tbl_Productos.getModel();
        //Mensaje para seleccionar la opción de eliminar o cambiar cantidad 
        int opcion = JOptionPane.showOptionDialog(
                this,
                "Seleccione opcion",
                "Selector de opciones",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono por defecto.
                new Object[]{"Eliminar", "Cambiar cantidad"}, // null para YES, NO y CANCEL
                "opcion 1");

        if (opcion == 0) {
            // Opción para eliminar el producto, se usa el método  eliminarProductoV
            boolean m = metodos.eliminarProductoV(String.valueOf(modeloProductos.getValueAt(seleccion, 6)), String.valueOf(modeloProductos.getValueAt(seleccion, 5)), String.valueOf(modeloProductos.getValueAt(seleccion, 7)));
            if (m == true) {
                //Mensaje de confirmación 
                JOptionPane.showMessageDialog(null, "Producto eliminado correctamente");
                llenarTablaVentas();
                limpiarTablaProductos();
            }
        }else if(opcion == 1){
            //Opción para actualizar la cantidad, se válida que el número sea entero 
            String numero = JOptionPane.showInputDialog("Ingrese la nueva cantidad");
            if (numero.matches("^\\d+$")) {
                int numeroInt = Integer.parseInt(numero);
                //Mensaje de confirmación 
                boolean res = metodos.modificarCantidadP(numeroInt, String.valueOf(modeloProductos.getValueAt(seleccion, 6)), String.valueOf(modeloProductos.getValueAt(seleccion, 7)));
                JOptionPane.showMessageDialog(null, "" + res);
                llenarTablaVentas();
                limpiarTablaProductos();
            } else {
                JOptionPane.showMessageDialog(null, "El numero tiene que ser positivo", "Error", JOptionPane.WARNING_MESSAGE);
            }

        }
        
    }//GEN-LAST:event_tbl_ProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_Productos;
    private javax.swing.JTable tbl_ventas;
    // End of variables declaration//GEN-END:variables
}
